spring:
  application:
    name: bookstore-api

  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?allowMultiQueries=true
    username: bookstore
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      connection-timeout: 15000
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bookstore.bookstore_api.user.domain.entity,com.bookstore.bookstore_api.order.domain.entity,com.bookstore.bookstore_api.product.domain.entity,com.bookstore.bookstore_api.log.domain.entity
  configuration:
    map-underscore-to-camel-case: true

naver:
  api:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}

jwt:
  secret: VlwEyVlPKZ6yV9yVlwEyVlPKZ6yV9yVlwEyVlPKZ6yV9yVlwEyVlPKZ6yV9y 
  expiration: 3600000 # 1시간 (밀리초 단위)
